name: bjj
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  flutter_image_slider: ^0.0.2
  smooth_page_indicator: ^1.1.0
  dots_indicator: ^3.0.0
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.13.0
  firebase_storage: ^11.5.0
  firebase_core: ^2.23.0
  fluttertoast: ^8.2.4
  flutter_otp_text_field: ^1.1.0+2
  get: ^4.6.5
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  video_uploader: ^1.2.0
  video_player: ^2.8.1
  file_picker: ^6.1.1
  chewie: ^1.7.4
  youtube_player_flutter: ^8.1.2
  flutter_svg: ^2.0.9
  get_storage: ^2.1.1
  url_launcher: ^6.2.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/applogo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
