// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ3dF8h3estnsnecoW-10pv84WVISV4TM',
    appId: '1:705368097694:web:700f981a77af7a0294cc8f',
    messagingSenderId: '705368097694',
    projectId: 'bjjtraining-964ad',
    authDomain: 'bjjtraining-964ad.firebaseapp.com',
    storageBucket: 'bjjtraining-964ad.appspot.com',
    measurementId: 'G-LL7F2RXBBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz2TPHPhvH2BF7a3BUQiR7eJxINHA5cpk',
    appId: '1:705368097694:android:d44de6b930d8e4dd94cc8f',
    messagingSenderId: '705368097694',
    projectId: 'bjjtraining-964ad',
    storageBucket: 'bjjtraining-964ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsopBqa1doxtRfjvfLFhqMIsn2k4TJfac',
    appId: '1:705368097694:ios:2f83c2fa8d8632c194cc8f',
    messagingSenderId: '705368097694',
    projectId: 'bjjtraining-964ad',
    storageBucket: 'bjjtraining-964ad.appspot.com',
    iosBundleId: 'com.example.bjj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsopBqa1doxtRfjvfLFhqMIsn2k4TJfac',
    appId: '1:705368097694:ios:c0e1d7ce0ee5d63b94cc8f',
    messagingSenderId: '705368097694',
    projectId: 'bjjtraining-964ad',
    storageBucket: 'bjjtraining-964ad.appspot.com',
    iosBundleId: 'com.example.bjj.RunnerTests',
  );
}
